config/routes.rb
Rails.application.routes.draw do
  get 'kadais/list' => 'kadais#list', as: 'list_kadais'
  
  resources :kadais do
    resources :tasks, :only =>[:create,:edit,:update]
  end
  
  resources :persons
  
  resources :statuses
  
  resources :categories
  
  resources :routines
  
  
  get 'tasks/:task_id/edit' => 'tasks#edit1', as: 'edit_task'
  get 'tasks' => 'tasks#index'
  patch 'tasks/:id' => 'tasks#update1', as: 'task'
  
  get 'tasks/calender' => 'tasks#calender', as: 'tasks_calender'
  
  post 'kadais/filter/' => 'kadais#filter', as: 'kadais_filter'
  post 'tasks/filter/' => 'tasks#filter', as: 'tasks_filter'
  
  root 'kadais#index'

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
    def index
        @statuses = Status.all.order('code asc')
    end
    
    def new
        @status = Status.new
    end
    
    def create
        @status = Status.new(status_params)
        @status.save
        redirect_to statuses_path
    end
    
    def edit
        @status = Status.find(params[:id])
    end
    
    def update
        @status =Status.find(params[:id]).update(status_params)
        redirect_to statuses_path
    end
    
    private
        # Use callbacks to share common setup or constraints between actions.
        def set_status
          @status = Status.find(params[:id])
        end
    
        def status_params
            params.require(:status).permit(:phase,:code)
        end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/edit.html.erb
<%= form_for @status do |f| %>
  <div class="field">
    <%= f.label :code, '識別コード' %><br>
    <%= f.text_field :code %>
  </div>
  
  <div class="field">
    <%= f.label :phase, '状態' %><br>
    <%= f.text_field :phase %>
  </div>
  
  <div class="actions">
    <%= f.submit("更新する") %>
  </div>
<% end %>

app/views/statuses/index.html.erb
<h2>進捗状態一覧</h2>

<table>
    <thead>
        <tr>
            <th></th>
            <th>識別コード</th>
            <th>状態</th>
        </tr>
    </thead>
    
    <tbody>
        <% @statuses.each do |status| %>
            <tr>
                <td><%= link_to '編集',edit_status_path(status) %></td>
                <td><%= status.code %></td>
                <td><%= status.phase %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<p><%= link_to '状態を追加する', new_status_path %></p>

app/views/statuses/new.html.erb
<%= form_for :status, url: statuses_path do |f| %>
  <div class="field">
      <%= f.label :code, '番号' %><br>
      <%= f.text_field :code, placeholder: "識別コードを入力" %> 
  </div>
  <div class="field">
      <%= f.label :phase, '進捗' %><br>
      <%= f.text_field :phase, placeholder: "進捗状態を入力" %> 
  </div>
  <div class="actions">
    <%= f.submit("新規投稿") %>
  </div>
<% end %>