config/routes.rb
Rails.application.routes.draw do
  get 'kadais/list' => 'kadais#list', as: 'list_kadais'
  
  resources :kadais do
    resources :tasks, :only =>[:create,:edit,:update]
  end
  
  resources :persons
  
  resources :statuses
  
  resources :categories
  
  resources :routines
  
  
  get 'tasks/:task_id/edit' => 'tasks#edit1', as: 'edit_task'
  get 'tasks' => 'tasks#index'
  patch 'tasks/:id' => 'tasks#update1', as: 'task'
  
  get 'tasks/calender' => 'tasks#calender', as: 'tasks_calender'
  
  post 'kadais/filter/' => 'kadais#filter', as: 'kadais_filter'
  post 'tasks/filter/' => 'tasks#filter', as: 'tasks_filter'
  
  root 'kadais#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :kadai
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @tasks = Task.where.not(status:["04_Invaild"]).order('due_date DESC')
    end
    
    def create
        @kadai = Kadai.find(params[:kadai_id])
        @task = @kadai.tasks.create(params.require(:task).permit(:status, :do_person, :task, :plan_hour, :due_date, :actual_hour, :do_date))
        redirect_to kadai_path(params[:kadai_id])
    end
    
    def edit
        @kadai = Kadai.find(params[:kadai_id])
        @task = @kadai.tasks.find(params[:id])
    end
    
    def edit1
        @task = Task.find(params[:task_id])
    end
    
    def update
        @kadai = Kadai.find(params[:kadai_id])
        @task = @kadai.tasks.find(params[:id]).update(params.require(:task).permit(:status, :task, :do_person, :plan_hour, :due_date, :actual_hour, :do_date))
        redirect_to kadai_path(params[:kadai_id])
    end
    
    def update1
        @task = Task.find(params[:id]).update(params.require(:task).permit(:status, :task, :do_person, :plan_hour, :due_date, :actual_hour, :do_date))
        redirect_to kadais_path
    end
    
    def calender
        @tasks = Task.where.not(status: ["04_Invaild","99_Close",""]).order('due_date ASC')
        @persons_for_options = Hash.new
        Person.all.each do |person|
           @persons_for_options.store(person.name, person.name)
        end
    end
    
    def filter
        @tasks = Task.where(do_person: params[:person]).where.not(status:["04_Invaild",""]).where.not(due_date: "").order('due_date DESC')
        @persons_for_options = Hash.new
        Person.all.each do |person|
           @persons_for_options.store(person.name, person.name)
        end
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_calender.html.erb
<%= form_tag tasks_filter_path do %>
    <%= select_tag :person, options_for_select(@persons_for_options), :include_blank => true %>
    <%= submit_tag "フィルターをかける" %>
<% end %>

<table id="tasks_calender"  class="responsive">
    <thead>
        <th class="width_30">タスク<br>番号</th>
        <th class="width_30">課題<br>番号</th>
        <th class="width_30">担当者</th>
        <th class="width_200">タスク内容</th>
        <th class="width_40">実施<br>予定日</th>
        <% for i in -5..15 do%>
            <% if i == 0 then %>
                <th class="emp width_40"><%= (Date.today+i).strftime("%m/%d") %><br>Today</th>
            <% else %>
                <th class="width_40"><%= (Date.today+i).strftime("%m/%d") %></th>
            <% end %>
        <% end %>
    </thead>
    <tbody>
        <% @tasks.each do |task| %>
        <tr>
            <td class="edit"><%= link_to task.id, edit_task_path(task) %></td>
            <td class="edit"><%= link_to task.kadai_id, edit_kadai_path(task.kadai_id) %></td>
            <td><%= task.do_person %></td>
            <td><%= task.task %></td>
            <td><%= task.due_date.strftime("%m/%d") %></td>
            <% for i in -5..15 do %>
                <% if task.due_date == (Date.today+i) then %>
                    <td style="background-color:#A2DBA8; color:#ffffff; text-align:center;"><%= task.plan_hour %></td>
                <% else %>
                    <td></td>
                <% end %>
            <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/tasks/calender.html.erb
<table id="tasks_calender"  class="responsive">
    <thead>
        <th class="width_30">タスク<br>番号</th>
        <th class="width_30">課題<br>番号</th>
        <th class="width_30">担当者</th>
        <th class="width_200">タスク内容</th>
        <th class="width_40">実施<br>予定日</th>
        <% for i in -5..15 do%>
            <% if i == 0 then %>
                <th class="emp width_40"><%= (Date.today+i).strftime("%m/%d") %><br>Today</th>
            <% else %>
                <th class="width_40"><%= (Date.today+i).strftime("%m/%d") %></th>
            <% end %>
        <% end %>
    </thead>
    <tbody>
        <% @tasks.each do |task| %>
        <tr>
            <td class="edit"><%= link_to task.id, edit_task_path(task) %></td>
            <td class="edit"><%= link_to task.kadai_id, edit_kadai_path(task.kadai_id) %></td>
            <td><%= task.do_person %></td>
            <td><%= task.task %></td>
            <td><%= task.due_date.strftime("%m/%d") %></td>
            <% for i in -5..15 do %>
                <% if task.due_date == (Date.today+i) then %>
                    <td style="background-color:#A2DBA8; color:#ffffff; text-align:center;"><%= task.plan_hour %></td>
                <% else %>
                    <td></td>
                <% end %>
            <% end %>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/tasks/edit.html.erb
<h2>タスクの編集</h2>

タスク番号：<%= params[:id] %></br>
課題番号：<%= params[:kadai_id] %>

<%= form_for [@kadai, @task] do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status, '状態' %><br>
    <%= f.collection_select :status, Status.all.order('code ASC'), :phase, :phase %>
  </div>
  <div class="field">
    <%= f.label :task,'タスク内容' %><br>
    <%= f.text_area :task, rows:5 %>
  </div>
  <div class="field">
    <%= f.label :do_person,'担当者' %><br>
    <%= f.collection_select :do_person,Person.all, :name, :name %>
  </div>
  <div class="field">
    <%= f.label :plan_hour,'予定作業時間(h)' %><br>
    <%= f.text_field :plan_hour %>
  </div>
  <div class="field">
    <%= f.label :due_date, '実施予定日' %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :actual_hour,'実績作業時間(h)' %><br>
    <%= f.text_field :actual_hour %>
  </div>
  <div class="field">
    <%= f.label :do_date,'実施日' %><br>
    <%= f.date_select :do_date %>
  </div>

  <div class="actions">
    <%= f.submit("更新する") %>
  </div>
<% end %>

app/views/tasks/edit1.html.erb
<h2>タスクの編集</h2>

タスク番号：<%= params[:id] %></br>

<%= form_for @task do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status, '状態' %><br>
    <%= f.collection_select :status,Status.all.order('code ASC'), :phase, :phase%>
  </div>
  <div class="field">
    <%= f.label :task,'タスク内容' %><br>
    <%= f.text_field :task %>
  </div>
  <div class="field">
    <%= f.label :do_person,'担当者' %><br>
    <%= f.collection_select :do_person,Person.all, :name, :name %>
  </div>
  <div class="field">
    <%= f.label :plan_hour,'予定作業時間(h)' %><br>
    <%= f.text_field :plan_hour %>
  </div>
  <div class="field">
    <%= f.label :due_date, '実施予定日' %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :actual_hour,'実績作業時間(h)' %><br>
    <%= f.text_field :actual_hour %>
  </div>
  <div class="field">
    <%= f.label :do_date,'実施日' %><br>
    <%= f.date_select :do_date %>
  </div>

  <div class="actions">
    <%= f.submit("更新する") %>
  </div>
<% end %>

app/views/tasks/filter.html.erb
<%= render 'calender' %>

app/views/tasks/index.html.erb
<h2>タスク一覧</h2>
<table class="responsive">
  <thead>
    <tr>
      <th>タスク番号</th>
      <th>課題番号</th>
      <th>状態</th>
      <th>担当者</th>
      <th>タスク内容</th>
      <th>予定作業時間(h)</th>
      <th>実施予定日</th>
      <th>実績作業時間(h)</th>
      <th>実施日</th>
      <th></th>
    </tr>
  </thead>
  
  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= task.id %></td>
      <td><%= task.kadai_id %></td>
      <td><%= task.status %></td>
      <td><%= task.do_person %></td>
      <td><%= task.task %></td>
      <td><%= task.plan_hour %></td>
      <td><%= task.due_date %></td>
      <td><%= task.actual_hour %></td>
      <td><%= task.do_date %></td>
      <td class="edit"><%= link_to '更新', edit_task_path(task) %></td>
    </tr>
    <% end %>
  </tbody>
</table>