config/routes.rb
Rails.application.routes.draw do
  get 'kadais/list' => 'kadais#list', as: 'list_kadais'
  
  resources :kadais do
    resources :tasks, :only =>[:create,:edit,:update]
  end
  
  resources :persons
  
  resources :statuses
  
  resources :categories
  
  resources :routines
  
  
  get 'tasks/:task_id/edit' => 'tasks#edit1', as: 'edit_task'
  get 'tasks' => 'tasks#index'
  patch 'tasks/:id' => 'tasks#update1', as: 'task'
  
  get 'tasks/calender' => 'tasks#calender', as: 'tasks_calender'
  
  post 'kadais/filter/' => 'kadais#filter', as: 'kadais_filter'
  post 'tasks/filter/' => 'tasks#filter', as: 'tasks_filter'
  
  root 'kadais#index'

end

app/models/kadai.rb
class Kadai < ActiveRecord::Base
    has_many :tasks
end

app/controllers/kadais_controller.rb
class KadaisController < ApplicationController
  before_action :set_kadai, only: [:show, :edit, :update, :destroy]

  # GET /kadais
  # GET /kadais.json
  def index
    @kadais = Kadai.where.not(status: ["04_Invaild", "99_Close"]).order('due_date DESC')
    @tasks = Task.where.not(status:["04_Invaild", "99_Close"]).order("due_date ASC")
    @persons_for_options = Hash.new
    Person.all.each do |person|
      @persons_for_options.store(person.name, person.name)
    end
  end
  
  def filter
    @kadais = Kadai.where(do_person: params[:person]).where.not(status: ["04_Invaild", "99_Close"]).order('due_date DESC')
    @tasks = Task.where(do_person: params[:person]).where.not(status: ["04_Invaild", "99_Close"]).order("due_date ASC")
    @persons_for_options = Hash.new
    Person.all.each do |person|
      @persons_for_options.store(person.name, person.name)
    end
  end
  
  #GET /kadais/list
  def list
    @kadais = Kadai.where.not(status: "04_Invaild").order('due_date DESC')
  end

  # GET /kadais/1
  # GET /kadais/1.json
  def show
    @kadai = Kadai.find(params[:id])
    @task = Task.new
  end

  # GET /kadais/new
  def new
    @kadai = Kadai.new
  end

  # GET /kadais/1/edit
  def edit
  end

  # POST /kadais
  # POST /kadais.json
  def create
    @kadai = Kadai.new(kadai_params)

    respond_to do |format|
      if @kadai.save
        format.html { redirect_to @kadai, notice: 'Kadai was successfully created.' }
        format.json { render :show, status: :created, location: @kadai }
      else
        format.html { render :new }
        format.json { render json: @kadai.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kadais/1
  # PATCH/PUT /kadais/1.json
  def update
    respond_to do |format|
      if @kadai.update(kadai_params)
        format.html { redirect_to @kadai, notice: 'Kadai was successfully updated.' }
        format.json { render :show, status: :ok, location: @kadai }
      else
        format.html { render :edit }
        format.json { render json: @kadai.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kadais/1
  # DELETE /kadais/1.json
  def destroy
    @kadai.destroy
    respond_to do |format|
      format.html { redirect_to kadais_url, notice: 'Kadai was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kadai
      @kadai = Kadai.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kadai_params
      params.require(:kadai).permit(:status, :vote_date, :vote_person, :category, :subject, :level, :do_person, :goal, :due_date, :plan_hour, :actual_hour, :end_date)
    end
  
end

app/helpers/kadais_helper.rb
module KadaisHelper
end

app/views/kadais/_form.html.erb
<%= form_for(@kadai) do |f| %>
  <% if @kadai.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kadai.errors.count, "error") %> prohibited this kadai from being saved:</h2>

      <ul>
      <% @kadai.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status, '状態' %><br>
    <%= f.select :status, ["01_Open"]%>
  </div>
  <div class="field">
    <%= f.label :vote_date,'起票日' %><br>
    <%= f.date_select :vote_date %>
  </div>
  <div class="field">
    <%= f.label :vote_person,'起票者' %><br>
    <%= f.collection_select :vote_person, Person.all, :name,:name %>
  </div>
  <div class="field">
    <%= f.label :category,'カテゴリー' %><br>
    <%= f.collection_select :category,Category.all, :name,:name %>
  </div>
  <div class="field">
    <%= f.label :subject, '課題' %><br>
    <%= f.text_area :subject, rows:5 %>
  </div>
  <div class="field">
    <%= f.label :level,'重要度' %><br>
    <%= f.collection_select :level, Level.all, :level, :level %>
  </div>
  <div class="field">
    <%= f.label :do_person,'対応担当者' %><br>
    <%= f.collection_select :do_person, Person.all, :name,:name %>
  </div>
  <div class="field">
    <%= f.label :goal,'完了基準' %><br>
    <%= f.text_area :goal, rows:5 %>
  </div>
  <div class="field">
    <%= f.label :due_date,'期日' %><br>
    <%= f.date_select :due_date %>
  </div>
  <!-- div class="field">
    <%= f.label :end_date, '完了日' %><br>
    <%= f.date_select :end_date %>
  </div -->
  <div class="actions">
    <%= f.submit("新規投稿") %>
  </div>
<% end %>

app/views/kadais/_formedit.html.erb
<%= form_for(@kadai) do |f| %>
  <% if @kadai.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kadai.errors.count, "error") %> prohibited this kadai from being saved:</h2>

      <ul>
      <% @kadai.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status, '状態' %><br>
    <%= f.collection_select :status, Status.all, :phase, :phase %>
  </div>
  <div class="field">
    <%= f.label :vote_date,'起票日' %><br>
    <%= f.date_select :vote_date %>
  </div>
  <div class="field">
    <%= f.label :vote_person,'起票者' %><br>
    <%= f.collection_select :vote_person, Person.all, :name,:name %>
  </div>
  <div class="field">
    <%= f.label :category,'カテゴリー' %><br>
    <%= f.collection_select :category,Category.all, :name,:name %>
  </div>
  <div class="field">
    <%= f.label :subject, '課題' %><br>
    <%= f.text_area :subject, rows:5 %>
  </div>
  <div class="field">
    <%= f.label :level,'重要度' %><br>
    <%= f.collection_select :level, Level.all, :level, :level %>
  </div>
  <div class="field">
    <%= f.label :do_person,'対応担当者' %><br>
    <%= f.collection_select :do_person, Person.all, :name,:name %>
  </div>
  <div class="field">
    <%= f.label :goal,'完了基準' %><br>
    <%= f.text_area :goal, rows:5 %>
  </div>
  <div class="field">
    <%= f.label :due_date,'期日' %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :end_date, '完了日' %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit("更新する") %>
  </div>
<% end %>

app/views/kadais/_index.html.erb
<p id="notice"><%= notice %></p>

<p><%= link_to '業務カレンダーを見る', routines_path %></p>

<%= form_tag kadais_filter_path do %>
    <%= select_tag :person, options_for_select(@persons_for_options), :include_blank => true %>
    <%= submit_tag "フィルターをかける" %>
<% end %>

<h2>課題一覧</h2>

<table class="responsive">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>状態</th>
      <th>カテゴリー</th>
      <th>重要度</th>
      <th>対応担当者</th>
      <th>課題内容（現状記述）</th>
      <th>期日</th>
      <th>進捗状況</th>
    </tr>
  </thead>

  <tbody>
    <% @kadais.each do |kadai| %>
      <tr>
        <td class="edit"><%= link_to '詳細', kadai %></td>
        <td class="edit"><%= link_to '編集', edit_kadai_path(kadai) %></td>
        <td data-label='状態'><%= kadai.status %></td>
        <td data-label='カテゴリー'><%= kadai.category %></td>
        <td data-label='重要度'><%= kadai.level %></td>
        <td data-label='対応担当者'><%= kadai.do_person %></td>
        <td data-label='内容'><%= kadai.subject %></td>
        <td data-label='期日'><%= kadai.due_date %></td>
        <td data-label='進捗'><%= kadai.tasks.sum(:plan_hour).round(1) %>h(<%= kadai.tasks.sum(:actual_hour).round(1) %>h完了)</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to '新規課題を追加', new_kadai_path %><br></p>

<p><%= link_to '終了した課題も見たい方はこちら', list_kadais_path %></p>


<h2>タスク一覧 <%= link_to 'タスクカレンダー', tasks_calender_path %></h2>
<table class="responsive">
  <thead>
    <tr>
      <th></th>
      <th>タスク内容</th>
      <th>状態</th>
      <th>担当者</th>
      <th>進捗状況</th>
      <th>完了予定日</th>
    </tr>
  </thead>
  
  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td class="edit"><%= link_to '更新', edit_task_path(task) %></td>
      <td><%= task.task %></td>
      <td><%= task.status %></td>
      <td><%= task.do_person %></td>
      <td><%= task.plan_hour %>h<br>(<%= task.actual_hour %>h完了)</td>
      <% if task.due_date < Date.today then %>
        <td class="emp"><%= task.due_date.strftime('%m/%d') %></td>
      <% elsif task.due_date == Date.today then %>
        <td class="today"><%= task.due_date.strftime('%m/%d') %></td>
      <% else %>
        <td><%= task.due_date.strftime('%m/%d') %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>


<h3>完了したタスクも見たい方はこちら</h3>
<%= link_to 'タスク一覧', tasks_path %>

<h3>担当者を追加する</h3>
<%= link_to '担当者の追加', persons_path %>

<h3>状態を追加する（課題・タスク共通）</h3>
<%= link_to '担当者の追加', statuses_path %>

<h3>カテゴリーを追加する</h3>
<%= link_to '担当者の追加', categories_path %>

app/views/kadais/edit.html.erb
<h1>課題の更新</h1>

<%= render 'formedit' %>

<%= link_to 'Show', @kadai %> |
<%= link_to 'Back', kadais_path %>

app/views/kadais/filter.html.erb
<%= render 'index' %>

app/views/kadais/index.html.erb
<p id="notice"><%= notice %></p>

<p><%= link_to '業務カレンダーを見る', routines_path %></p>

<h2>課題一覧</h2>

<table class="responsive">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>状態</th>
      <th>カテゴリー</th>
      <th>重要度</th>
      <th>対応担当者</th>
      <th>課題内容（現状記述）</th>
      <th>期日</th>
      <th>進捗状況</th>
    </tr>
  </thead>

  <tbody>
    <% @kadais.each do |kadai| %>
      <tr>
        <td class="edit"><%= link_to '詳細', kadai %></td>
        <td class="edit"><%= link_to '編集', edit_kadai_path(kadai) %></td>
        <td data-label='状態'><%= kadai.status %></td>
        <td data-label='カテゴリー'><%= kadai.category %></td>
        <td data-label='重要度'><%= kadai.level %></td>
        <td data-label='対応担当者'><%= kadai.do_person %></td>
        <td data-label='内容'><%= kadai.subject %></td>
        <td data-label='期日'><%= kadai.due_date %></td>
        <td data-label='進捗'><%= kadai.tasks.sum(:plan_hour).round(1) %>h(<%= kadai.tasks.sum(:actual_hour).round(1) %>h完了)</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to '新規課題を追加', new_kadai_path %><br></p>

<p><%= link_to '終了した課題も見たい方はこちら', list_kadais_path %></p>


<h2>タスク一覧 <%= link_to 'タスクカレンダー', tasks_calender_path %></h2>
<table class="responsive">
  <thead>
    <tr>
      <th></th>
      <th>タスク内容</th>
      <th>状態</th>
      <th>担当者</th>
      <th>進捗状況</th>
      <th>完了予定日</th>
    </tr>
  </thead>
  
  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td class="edit"><%= link_to '更新', edit_task_path(task) %></td>
      <td><%= task.task %></td>
      <td><%= task.status %></td>
      <td><%= task.do_person %></td>
      <td><%= task.plan_hour %>h<br>(<%= task.actual_hour %>h完了)</td>
      <% if task.due_date < Date.today then %>
        <td class="emp"><%= task.due_date.strftime('%m/%d') %></td>
      <% else %>
        <td><%= task.due_date.strftime('%m/%d') %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>


<h3>完了したタスクも見たい方はこちら</h3>
<%= link_to 'タスク一覧', tasks_path %>

<h3>担当者を追加する</h3>
<%= link_to '担当者の追加', persons_path %>

<h3>状態を追加する（課題・タスク共通）</h3>
<%= link_to '担当者の追加', statuses_path %>

<h3>カテゴリーを追加する</h3>
<%= link_to '担当者の追加', categories_path %>

app/views/kadais/list.html.erb
<p id="notice"><%= notice %></p>

<h2>課題一覧(終了した課題を含む)</h2>

<table class="responsive">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>状態</th>
      <th>カテゴリー</th>
      <th>重要度</th>
      <th>対応担当者</th>
      <th>課題内容（現状記述）</th>
      <th>期日</th>
      <th>進捗状況</th>
    </tr>
  </thead>

  <tbody>
    <% @kadais.each do |kadai| %>
      <tr>
        <td class="edit"><%= link_to '詳細', kadai %></td>
        <td class="edit"><%= link_to '編集', edit_kadai_path(kadai) %></td>
        <td data-label='状態'><%= kadai.status %></td>
        <td data-label='カテゴリー'><%= kadai.category %></td>
        <td data-label='重要度'><%= kadai.level %></td>
        <td data-label='対応担当者'><%= kadai.do_person %></td>
        <td data-label='内容'><%= kadai.subject %></td>
        <td data-label='期日'><%= kadai.due_date %></td>
        <td data-label='進捗'><%= kadai.tasks.sum(:plan_hour).round(1) %>h(<%= kadai.tasks.sum(:actual_hour).round(1)%>h完了)</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/kadais/new.html.erb
<h1>新しい課題を追加する</h1>

<%= render 'form' %>

<%= link_to 'Back', kadais_path %>

app/views/kadais/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= link_to '課題を編集', edit_kadai_path(@kadai) %> </p>

<table>
<tr>
  <td><strong>状態</strong></td>
  <td><%= @kadai.status %></td>
</tr>
<tr>
  <td><strong>起票日</strong></td>
  <td><%= @kadai.vote_date %></td>
</tr>
<tr>
  <td><strong>起票者</strong></td>
  <td><%= @kadai.vote_person %></td>
</tr>
<tr>
  <td><strong>カテゴリー</strong></td>
  <td><%= @kadai.category %></td>
</tr>
<tr>
  <td><strong>課題内容</strong></td>
  <td><%= @kadai.subject %></td>
</tr>
<tr>
  <td><strong>重要度</strong></td>
  <td><%= @kadai.level %></td>
</tr>
<tr>
  <td><strong>対応担当者</strong></td>
  <td><%= @kadai.do_person %></td>
</tr>
<tr>
  <td><strong>完了基準</strong></td>
  <td><%= @kadai.goal %></td>
</tr>
<tr>
  <td><strong>期日</strong></td>
  <td><%= @kadai.due_date %></td>
</tr>
<tr>
  <td><strong>予定作業時間(h）</strong></td>
  <td><%= @kadai.tasks.sum(:plan_hour).round(1) %></td>
</tr>
<tr>
  <td><strong>実績作業時間(h)</strong></td>
  <td><%= @kadai.tasks.sum(:actual_hour).round(1) %></td>
</tr>
<tr>
  <td><strong>完了日</strong></td>
  <td><%= @kadai.end_date %></td>
</tr>
</table>



<h3>関連タスク</h3>
<table class="responsive">
  <thead>
    <tr>
      <th>タスク番号</th>
      <th>タスク内容</th>
      <th>状態</th>
      <th>担当者</th>
      <th>予定作業時間(h)</th>
      <th>実施予定日</th>
      <th>実績作業時間(h)</th>
      <th>実施日</th>
      <th></th>
    </tr>
  </thead>
  
  <tbody>
    <% @kadai.tasks.where.not(status:"04_Invaild").order('do_date DESC').each do |task| %>
    <tr>
      <td><%= task.id %></td>
      <td><%= task.task %></td>
      <td><%= task.status %></td>
      <td><%= task.do_person %></td>
      <td><%= task.plan_hour %></td>
      <td><%= task.due_date %></td>
      <td><%= task.actual_hour %></td>
      <td><%= task.do_date %></td>
      <td><%= link_to 'Edit', edit_kadai_task_path(@kadai,task) %></td>
    </tr>
    <% end %>
  </tbody>
</table>


<h3>タスクを追加する</h3>
<%= form_for [@kadai, @task] do |f| %>
  <p>タスク内容:</p><p><%= f.text_field :task %></p>
  <p>状態:</p><p><%= f.collection_select :status, Status.all.order('code ASC'), :phase, :phase %></p>
  <p>担当者:</p><p><%= f.collection_select :do_person, Person.all, :name, :name %></p>
  <p>予定作業時間:</p><p><%= f.text_field :plan_hour %></p>
  <p>実施予定日:</p><p><%= f.date_select :due_date %></p>

  <%= f.submit '新規タスクを追加' %>
<% end %>


<%= link_to 'Topに戻る', kadais_path %>